/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.coba3;

/**
 *
 * @author luxxzy
 */
public class TugasModul10 extends javax.swing.JFrame {

    /**
     * Creates new form TugasModul10
     */
    public TugasModul10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        eData1 = new javax.swing.JTextField();
        eData2 = new javax.swing.JTextField();
        eHasil = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menFile = new javax.swing.JMenu();
        menProses = new javax.swing.JMenu();
        meltBersih = new javax.swing.JMenuItem();
        menPersegiPanjang = new javax.swing.JMenu();
        meltLuasPersegiPanjang = new javax.swing.JMenuItem();
        meltKelilingPersegiPanjang = new javax.swing.JMenuItem();
        menSegitiga = new javax.swing.JMenu();
        meltLuasSegitiga = new javax.swing.JMenuItem();
        meltKelilingSegitiga = new javax.swing.JMenuItem();
        menLingkaran = new javax.swing.JMenu();
        meltLuasLingkaran = new javax.swing.JMenuItem();
        meltKelilingLingkaran = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data 1");

        jLabel2.setText("Data 2");

        jLabel3.setText("Hasil");

        menFile.setText("File");
        jMenuBar1.add(menFile);

        menProses.setText("Proses");

        meltBersih.setText("Bersih");
        menProses.add(meltBersih);

        menPersegiPanjang.setText("Persegi Panjang");

        meltLuasPersegiPanjang.setText("Luas");
        meltLuasPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltLuasPersegiPanjangActionPerformed(evt);
            }
        });
        menPersegiPanjang.add(meltLuasPersegiPanjang);

        meltKelilingPersegiPanjang.setText("Keliling");
        meltKelilingPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltKelilingPersegiPanjangActionPerformed(evt);
            }
        });
        menPersegiPanjang.add(meltKelilingPersegiPanjang);

        menProses.add(menPersegiPanjang);

        menSegitiga.setText("Segitiga");

        meltLuasSegitiga.setText("Luas");
        meltLuasSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltLuasSegitigaActionPerformed(evt);
            }
        });
        menSegitiga.add(meltLuasSegitiga);

        meltKelilingSegitiga.setText("Keliling");
        meltKelilingSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltKelilingSegitigaActionPerformed(evt);
            }
        });
        menSegitiga.add(meltKelilingSegitiga);

        menProses.add(menSegitiga);

        menLingkaran.setText("Lingkaran");

        meltLuasLingkaran.setText("Luas");
        meltLuasLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltLuasLingkaranActionPerformed(evt);
            }
        });
        menLingkaran.add(meltLuasLingkaran);

        meltKelilingLingkaran.setText("Keliling");
        meltKelilingLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltKelilingLingkaranActionPerformed(evt);
            }
        });
        menLingkaran.add(meltKelilingLingkaran);

        menProses.add(menLingkaran);

        jMenuBar1.add(menProses);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(eData1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(eData2))
                    .addComponent(eHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(eHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meltKelilingLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltKelilingLingkaranActionPerformed
        // TODO add your handling code here:
        int radius = Integer.parseInt(eData1.getText());
        double perimeter = 2 * Math.PI * radius;
        eHasil.setText("Keliling Lingkaran: " + perimeter);
    }//GEN-LAST:event_meltKelilingLingkaranActionPerformed

    private void meltLuasPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltLuasPersegiPanjangActionPerformed
        // TODO add your handling code here:
         int length = Integer.parseInt(eData1.getText());
        int width = Integer.parseInt(eData2.getText());
        double area = length * width;
        eHasil.setText("Luas Persegi Panjang: " + area);
    }//GEN-LAST:event_meltLuasPersegiPanjangActionPerformed

    private void meltKelilingPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltKelilingPersegiPanjangActionPerformed
        // TODO add your handling code here:
        int length = Integer.parseInt(eData1.getText());
        int width = Integer.parseInt(eData2.getText());
        double perimeter = 2 * (length + width);
        eHasil.setText("Keliling Persegi Panjang: " + perimeter);
    }//GEN-LAST:event_meltKelilingPersegiPanjangActionPerformed

    private void meltLuasSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltLuasSegitigaActionPerformed
        // TODO add your handling code here:
        int base = Integer.parseInt(eData1.getText());
        int height = Integer.parseInt(eData2.getText());
        double area = 0.5 * base * height;
        eHasil.setText("Luas Segitiga: " + area);
    }//GEN-LAST:event_meltLuasSegitigaActionPerformed

    private void meltKelilingSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltKelilingSegitigaActionPerformed
        // TODO add your handling code here:
         int base = Integer.parseInt(eData1.getText());
        int side = Integer.parseInt(eData2.getText());
        double perimeter = base + 2 * side; // Assuming isosceles triangle for simplicity
        eHasil.setText("Keliling Segitiga: " + perimeter);
    }//GEN-LAST:event_meltKelilingSegitigaActionPerformed

    private void meltLuasLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltLuasLingkaranActionPerformed
        // TODO add your handling code here:
         int radius = Integer.parseInt(eData1.getText());
        double area = Math.PI * radius * radius;
        eHasil.setText("Luas Lingkaran: " + area);
    }//GEN-LAST:event_meltLuasLingkaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasModul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasModul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasModul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasModul10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugasModul10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eData1;
    private javax.swing.JTextField eData2;
    private javax.swing.JTextField eHasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem meltBersih;
    private javax.swing.JMenuItem meltKelilingLingkaran;
    private javax.swing.JMenuItem meltKelilingPersegiPanjang;
    private javax.swing.JMenuItem meltKelilingSegitiga;
    private javax.swing.JMenuItem meltLuasLingkaran;
    private javax.swing.JMenuItem meltLuasPersegiPanjang;
    private javax.swing.JMenuItem meltLuasSegitiga;
    private javax.swing.JMenu menFile;
    private javax.swing.JMenu menLingkaran;
    private javax.swing.JMenu menPersegiPanjang;
    private javax.swing.JMenu menProses;
    private javax.swing.JMenu menSegitiga;
    // End of variables declaration//GEN-END:variables
}
